apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: BOT_NAME
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gabela626-coder/boti-gitops
    targetRevision: main
    path: apps/BOT_NAME
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
