apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-hello
  template:
    metadata:
      labels:
        app: bot-hello
    spec:
      containers:
        - name: bot
          image: ghcr.io/gabela626-coder/bot-hello:2d88d761
          envFrom:
            - secretRef:
                name: bot-hello-secret
