apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-hello
  template:
    metadata:
      labels:
        app: bot-hello
    spec:
      containers:
        - name: web
          image: ghcr.io/gabela626-coder/bot-hello:9f258bfe
          ports:
            - containerPort: 8080
