apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-demo
  template:
    metadata:
      labels:
        app: bot-demo
    spec:
      containers:
        - name: bot
          image: ghcr.io/gabela626-coder/bot-demo:09bbec24
          envFrom:
            - secretRef:
                name: bot-demo-secret
